### ISSUE TITLE
如何新建WXEntryACtivity集成Activity  

### ISSUE THREAD

**Issue by k3v1n-uncle** [pj0579/flutter_wechat#1]
如何新建WXEntryACtivity集成Activity

**Comment by pj0579** [comment]
如果想要响应微信resp需要在mainActivity同级目录下创建wxapi文件夹 下面新建WXEntryACtivity.java继承Activity

**Comment by pj0579** [comment]
具体参考https://github.com/pj0579/Flutter_E_Project
