### ISSUE TITLE
ios 运行时候提示没有ld: library not found for -lflutter_wechat

### ISSUE THREAD

**Issue by sidealice** [pj0579/flutter_wechat#3]
可否提供一个最简example是集成好的，方便检查哪里不对导致这个问题

**Comment by sidealice** [comment]
pod 安装的时候有显示
Downloading dependencies
Using Flutter (1.0.0)
Using WechatOpenSDK (1.8.2)
Using flutter_wechat (0.0.1)
Generating Pods project
Integrating client project

**Comment by pj0579** [comment]
这个问题是微信ios依赖库下载不下来，我后面改一改直接把依赖库放本地就行了

**Comment by sidealice** [comment]
更新下我这里的奇怪症状，我用xcode的编译部署到手机就会有这个错误提示，如果我用命令行flutter run 部署到手机就没错误。 是否有可能是我本地的问题？
