### ISSUE TITLE
微信支付一直返回-1

### ISSUE THREAD

**Issue by xiancong2016** [pj0579/flutter_wechat#4]
已经将所需的全部参数传进了SDK，但是一直报-1，没有任何提示，检查了好多次参数，实在找不到原因，请问一般返回-1或-2是什么原因？

**Comment by pj0579** [comment]
Android的是吗

**Comment by xiancong2016** [comment]
是的

**Comment by xiancong2016** [comment]
是的，卡住一天了
![image](https://user-images.githubusercontent.com/20508670/44561814-2650fc80-a789-11e8-81af-0a838fdca787.png)

**Comment by pj0579** [comment]
android支付activity需要添加在Manifest
<activity
    android:name=".wxapi.WXPayEntryActivity"
    android:exported="true"
    android:launchMode="singleTop">
    <intent-filter>
        <action android:name="android.intent.action.VIEW"/>
        <category android:name="android.intent.category.DEFAULT"/>
        <data android:scheme="your AppId"/>
    </intent-filter>
 </activity>

**Comment by pj0579** [comment]
Android在 Manifest添加
<activity
    android:name=".wxapi.WXPayEntryActivity"
    android:exported="true"
    android:launchMode="singleTop">
    <intent-filter>
        <action android:name="android.intent.action.VIEW"/>
        <category android:name="android.intent.category.DEFAULT"/>
        <data android:scheme="your AppId"/>
    </intent-filter>
 </activity>

**Comment by xiancong2016** [comment]
好的，我看看

**Comment by pj0579** [comment]
AndroidManifest.xml下添加
<activity
    android:name=".wxapi.WXPayEntryActivity"
    android:exported="true"
    android:launchMode="singleTop">
    <intent-filter>
        <action android:name="android.intent.action.VIEW"/>
        <category android:name="android.intent.category.DEFAULT"/>
        <data android:scheme="your AppId"/>
    </intent-filter>
 </activity>

**Comment by pj0579** [comment]
更新了readme你看一下

**Comment by xiancong2016** [comment]
嗯嗯，好的，谢谢

**Comment by pj0579** [comment]
测试使用暂时不维护了 有需要的请使用 https://github.com/OpenFlutter/fluwx
