### ISSUE TITLE
分享的时候提示类型不对，我找了一下不知道type的定义是怎么来的。

### ISSUE THREAD

**Issue by sidealice** [pj0579/flutter_wechat#6]
微信那里没有定义type的地方，不知道你的type=0是怎么做的。 

具体微信提示错误是：
由于不支持的分享类型，无法分享到微信。

**Comment by pj0579** [comment]
type 只是用来标识分享 朋友圈和好友

**Comment by pj0579** [comment]
测试使用暂时不维护了 有需要的请使用 https://github.com/OpenFlutter/fluwx
