### ISSUE TITLE
android如何添加WXEntryActivity，给个例子啊

### ISSUE THREAD

**Issue by wangyongpenga** [pj0579/flutter_wechat#7]

**Comment by JarvanMo** [comment]
@wangyongpenga https://github.com/OpenFlutter/fluwx/tree/master/example/android/app/src/main/kotlin/net/sourceforge/simcpux/wxapi 包名要和你申请微信时候的包名一样。

**Comment by pj0579** [comment]
测试使用暂时不维护了   有需要的请使用 https://github.com/OpenFlutter/fluwx
